[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "https://karolinaprus.netlify.app/*"
  to = "https://karolinaprus.pl/:splat"
  status = 301
  force = true
